root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/learnit ./cmd/learnit"
  entrypoint = ["./tmp/learnit"]
  exclude_dir = ["frontend", "tmp", ".git", ".learnit", "dist"]
  include_ext = ["go", "mod", "sum"]
  delay = 500
  kill_delay = "0.5s"

[log]
  time = true

[misc]
  clean_on_exit = true
